name: eva

channels:
  - conda-forge

dependencies:
  - python==3.12
  - pip
  - rdkit
  - numpy
  - scipy
  - pandas
  - scikit-learn

  - pip:
      - torch
      - tabpfn==8.0.8
      - lightning
      - descriptastorus
      - selfies
      - setuptools<82
      - aizynthfinder
      - ribs[all]
      - tensorboard

      - matplotlib
      - seaborn
      - huggingface_hub
      - rich
      - toml

      - pytest
      - fastparquet
      - chembl_structure_pipeline
